dist: bionic
language: python
python:
  - "3.6"
  - "3.8"
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-contrib-12
before_install:
  - sudo -u postgres psql -U postgres -p 5433 -d postgres -c "alter user postgres with password 'hj38f3Ntr';"
install:
  - pip install -r requirements.txt
script:
  - export PG_USER="postgres" && export PG_PASSWORD="hj38f3Ntr" && export PG_PORT=5433
  - python3 -m coverage run ./manage.py test
  - codecov
  - python3 -m flake8 --max-line-length=120 --exclude=./fms_core/migrations/ ./fms_core/ ./fms/
