server {
    listen 8080;
    listen [::]:8080;

    server_name localhost;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /data/freezeman/backend/staticfiles/;
    }

    location /media/ {
        alias /data/freezeman/backend/media/;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/data/freezeman/backend/fms/fms.sock;
    }
}
