FROM docker.io/library/debian:bookworm-20240612-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git python3.11-dev python3.11-venv postgresql-server-dev-15 uwsgi

COPY . /app
WORKDIR /app/backend


RUN python3.11 -m venv env && \
    . env/bin/activate && \
    pip install --no-cache-dir -r requirements.txt

CMD ["uwsgi", "--ini", "-"]
