# Generated by Django 3.0.8 on 2020-07-06 23:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0003_v1_3_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerRename',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fms_core.container',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
