# Generated by Django 3.1 on 2021-03-03 19:08

from django.db import migrations, models, transaction
import django.db.models.deletion
import json
from datetime import datetime, timedelta

from ..utils import float_to_decimal


def test(apps, schema_editor):
    Sample = apps.get_model("fms_core", "Sample")
    ProcessSample = apps.get_model("fms_core", "ProcessSample")

    for sample in Sample.objects.all():
        len_vh = len(sample.volume_history)
        len_ps = len(ProcessSample.objects.filter(source_sample_id=sample.id))
        if len_vh != len_ps + 1:
            print(f'Sample ID: #{sample.id} not conform. len vh is #{len_vh} and len ps is #{len_ps}')




class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0018_test4'),
    ]

    operations = [
        # migrations.RunPython(
        #     test,
        #     migrations.RunPython.noop
        # ),



    ]




