# Generated by Django 3.1 on 2021-03-02 18:25
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0021_v3_3_0'),
    ]

    operations = [
        # Migrations related to Project
        migrations.CreateModel(
            name='Project',
            fields=[
                #Project Model
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project.', max_length=200)),
                ('principal_investigator', models.CharField(blank=True, help_text='The principal investigator responsible for the project', max_length=200)),
                ('requestor_name', models.CharField(blank=True, help_text='The name of the requestor of the project', max_length=200)),
                ('requestor_email', models.CharField(blank=True,  help_text='The email of the requestor of the project', max_length=200)),
                ('targeted_end_date', models.DateTimeField(blank=True, help_text='Targeted date to conclude the project.')),
                ('status', models.CharField(help_text='The status of the project', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Other relevant information about the project.')),
                #Tracked Model
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the instance was created.')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='fms_core_project_creation',
                                                 to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date the instance was modified.')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='fms_core_project_modification',
                                                 to=settings.AUTH_USER_MODEL)),
                ('deleted', models.BooleanField(default=False, help_text='Whether this instance has been deleted.')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='Project associated with the sample.',
                on_delete=django.db.models.deletion.PROTECT,
                to='fms_core.project'),
        )
    ]