# Generated by Django 3.1 on 2021-08-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0021_v3_3_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='individual',
            field=models.ForeignKey(blank=True, help_text='Individual associated with the sample.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='fms_core.individual'),
        ),
    ]
