# Generated by Django 3.1 on 2021-10-21 21:20

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
import reversion

ADMIN_USERNAME = 'biobankadmin'


def create_sample_qc_objects(apps, schema_editor):
    Platform = apps.get_model("fms_core", "Platform")
    InstrumentType = apps.get_model("fms_core", "InstrumentType")
    Protocol = apps.get_model("fms_core", "Protocol")
    PropertyType = apps.get_model("fms_core", "PropertyType")
    ContentType = apps.get_model('contenttypes', 'ContentType')

    with reversion.create_revision(manage_manually=True):
        admin_user = User.objects.get(username=ADMIN_USERNAME)
        admin_user_id = admin_user.id

        reversion.set_comment("Create objects related to protocol Sample Quality Control")
        reversion.set_user(admin_user)

        # Create Platform and InstrumentType
        p = Platform.objects.create(name="Quality Control", created_by_id=admin_user_id, updated_by_id=admin_user_id)
        reversion.add_to_revision(p)

        # DICT { TYPE : PLATFORM }
        INSTRUMENT_TYPES = {
            "PicoGreen": "Quality Control",
            "Qubit": "Quality Control",
            "Agarose Gel": "Quality Control",
            "TapeStation": "Quality Control",
            "NanoDrop": "Quality Control",
            "Tecan Absorbance": "Quality Control",
            "BioAnalyzer": "Quality Control",
            "Caliper LabChip": "Quality Control",
        }
        for type in INSTRUMENT_TYPES:
            platform = Platform.objects.get(name=INSTRUMENT_TYPES[type])
            it = InstrumentType.objects.create(platform=platform,
                                               type=type,
                                               created_by_id=admin_user_id,
                                               updated_by_id=admin_user_id)

            reversion.add_to_revision(it)

        # Create PropertyType and Protocols
        PROPERTY_TYPES_BY_PROTOCOL = {
            "Sample Quality Control": [("Sample Quality QC Flag", "str"),
                                       ("Sample Quantity QC Flag", "str"),
                                       ("Measured Volume", "str"),
                                       ("Concentration",  "str"),
                                       ("RIN", "str"),
                                       ("Quantity Instrument", "str"),
                                       ("Quality Instrument", "str")],
        }
        protocol_content_type = ContentType.objects.get_for_model(Protocol)

        for protocol_name in PROPERTY_TYPES_BY_PROTOCOL.keys():
            protocol = Protocol.objects.create(name=protocol_name, created_by_id=admin_user_id, updated_by_id=admin_user_id)
            reversion.add_to_revision(protocol)

            for (property, value_type) in PROPERTY_TYPES_BY_PROTOCOL[protocol_name]:
                if property == 'RIN':
                    is_optional = True
                else:
                    is_optional = False

                pt = PropertyType.objects.create(name=property,
                                                 object_id=protocol.id,
                                                 content_type=protocol_content_type,
                                                 value_type=value_type,
                                                 is_optional=is_optional,
                                                 created_by_id=admin_user_id, updated_by_id=admin_user_id)
                reversion.add_to_revision(pt)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms_core', '0027_v3_5_0'),
    ]

    operations = [
        migrations.RunPython(
            create_sample_qc_objects,
            reverse_code=migrations.RunPython.noop,
        )
    ]