# Generated by Django 3.1 on 2021-10-21 21:20

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms_core', '0028_v3_5_0'),
    ]

    operations = [
        migrations.RunSQL(
            """
                DROP VIEW IF EXISTS fms_core_fullsample;
            """,
            migrations.RunSQL.noop
        ),
    ]