# Generated by Django 3.1 on 2022-04-04 16:21

from django.db import migrations, models
import reversion
from django.db.models import Q


def transfer_qc_flags(apps, schema_editor):
    Sample = apps.get_model("fms_core", "Sample")
    with reversion.create_revision(manage_manually=True):
        samples_with_qc_flags = Sample.objects.filter(Q(derived_samples__quality_flag__isnull=False) | Q(derived_samples__quantity_flag__isnull=False))
        for sample in samples_with_qc_flags:
            sample.quality_flag = sample.derived_samples.first().quality_flag
            sample.quantity_flag = sample.derived_samples.first().quantity_flag
            sample.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0033_v3_8_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='quality_flag',
            field=models.BooleanField(blank=True, choices=[(True, 'Passed'), (False, 'Failed')],
                                      help_text='Quality flag of the sample.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='quantity_flag',
            field=models.BooleanField(blank=True, choices=[(True, 'Passed'), (False, 'Failed')],
                                      help_text='Quantity flag of the sample.', max_length=20, null=True),
        ),
        migrations.RunPython(
            transfer_qc_flags,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='derivedsample',
            name='quality_flag',
        ),
        migrations.RemoveField(
            model_name='derivedsample',
            name='quantity_flag',
        ),
    ]
