# Generated by Django 3.1 on 2022-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0036_v3_9_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='alias',
            field=models.CharField(blank=True, null=True, help_text='Original individual name used by external client.', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='external_name',
            field=models.CharField(blank=True, null=True, help_text='Original project name used by external client.', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, null=True, help_text='Identifier to connect to an external system.', max_length=200),
        ),
    ]
