# Generated by Django 3.1 on 2022-07-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0039_v3_9_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdGenerator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
