# Generated by Django 3.1 on 2022-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0040_dataset_datasetfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='Date the dataset generation was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='datasetfile',
            name='validation_date',
            field=models.DateTimeField(blank=True, help_text='Date the dataset was validated.', null=True),
        ),
    ]
