# Generated by Django 3.1 on 2022-06-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0041_auto_20220623_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='dataset',
            field=models.ForeignKey(help_text='The dataset of the file', on_delete=django.db.models.deletion.PROTECT, related_name='files', to='fms_core.dataset'),
        ),
    ]
