# Generated by Django 3.1 on 2022-11-08 21:28

from django.db import migrations, models
from django.contrib.auth.models import User
import reversion
from typing import List


ADMIN_USERNAME = 'biobankadmin'

def set_needs_processing_flags(apps, schema_editor) :
    RunType = apps.get_model("fms_core", "RunType")

    with reversion.create_revision(manage_manually=True):
        admin_user = User.objects.get(username=ADMIN_USERNAME)
        admin_user_id = admin_user.id

        reversion.set_comment("Set needs_run_processing flags on DBNSEQ and Illumina run types.")
        reversion.set_user(admin_user)

        run_types = RunType.objects.all()

        for run_type in run_types:
            if(run_type.name == "DNBSEQ" or run_type.name=="Illumina"):
                run_type.needs_run_processing = True
            else:
                run_type.needs_run_processing = False
            run_type.save()
            reversion.add_to_reversion(run_type)

class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0045_v3_13_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtype',
            name='needs_run_processing',
            field=models.BooleanField(default=False, help_text='Run processing is expected for this run type.'),
        ),

         migrations.RunPython(
            set_needs_processing_flags,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
