# Generated by Django 3.1 on 2022-11-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0045_v3_13_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentrun',
            name='run_processing_launch_date',
            field=models.DateField(help_text='Date on which run processing was launched, if it has been launched.', null=True),
        ),
    ]
