# Generated by Django 3.1 on 2023-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0053_v4_3_0'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['coordinate'], name='fms_core_co_coordin_27d459_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['barcode'], name='fms_core_co_barcode_fdac5c_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['name'], name='fms_core_co_name_ec10e2_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['name'], name='fms_core_co_name_fc06c1_idx'),
        ),
        migrations.AddIndex(
            model_name='individual',
            index=models.Index(fields=['name'], name='fms_core_in_name_bbaf8d_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['type'], name='fms_core_in_type_id_8d8189_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='fms_core_pr_name_332150_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['creation_date'], name='fms_core_sa_creatio_c15eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='samplenextstep',
            index=models.Index(fields=['sample', 'step'], name='fms_core_sa_sample__ac44ad_idx'),
        ),
        migrations.AddIndex(
            model_name='samplenextstepbystudy',
            index=models.Index(fields=['sample_next_step', 'step_order', 'study'], name='fms_core_sa_sample__172375_idx'),
        ),
        migrations.AddIndex(
            model_name='steporder',
            index=models.Index(fields=['order', 'workflow'], name='fms_core_st_order_06777e_idx'),
        ),
    ]
