# Generated by Django 3.1 on 2023-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0053_v4_3_0'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['coordinate'], name='container_coordinate_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['barcode'], name='container_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['name'], name='container_name_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['name'], name='coordinate_name_idx'),
        ),
        migrations.AddIndex(
            model_name='individual',
            index=models.Index(fields=['name'], name='individual_name_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['type'], name='instrument_type_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['creation_date'], name='sample_creationdate_idx'),
        ),
        migrations.AddIndex(
            model_name='samplenextstep',
            index=models.Index(fields=['sample', 'step'], name='samplenextstep_sample_step_idx'),
        ),
        migrations.AddIndex(
            model_name='samplenextstepbystudy',
            index=models.Index(fields=['sample_next_step', 'step_order', 'study'], name='samplenextstepbystudy_samplenextstep_steporder_study_idx'),
        ),
        migrations.AddIndex(
            model_name='steporder',
            index=models.Index(fields=['order', 'workflow'], name='steporder_order_workflow_idx'),
        ),
    ]
