# Generated by Django 4.2.4 on 2023-08-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0055_v4_5_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetfile',
            name='size',
            field=models.IntegerField(default=1, help_text='Size of the dataset file.'),
            preserve_default=False,
        ),
    ]
