# Generated by Django 4.2.4 on 2023-09-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0056_v4_5_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the study.'),
        ),
    ]
