# Generated by Django 4.2.4 on 2024-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0066_v4_12_0'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['name'], name='metric_name_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['name', 'value_numeric'], name='metric_name_value_numeric_idx'),
        ),
    ]
