# Generated by Django 4.2.4 on 2024-10-17 17:30

from django.db import migrations, models
import reversion
from django.contrib.auth.models import User

ADMIN_USERNAME = 'biobankadmin'

def remove_instrument_type_for_user(apps, schema_editor):
  #  below described instrument are to be removed from being displayed to the front
  INSTRUMENT_TO_REMOVE = ["PicoGreen", "Qubit", "qPCR", "Spark 10M"]
  InstrumentType = apps.get_model("fms_core", "InstrumentType")
  with reversion.create_revision(manage_manually=True):
    admin_user = User.objects.get(username=ADMIN_USERNAME)

    reversion.set_comment("Remove instrument types from prefiller dropdown of sample qc dna/rna step.")
    reversion.set_user(admin_user)

    it = InstrumentType.objects.filter(type__in=INSTRUMENT_TO_REMOVE)
    for instrument in it:
        instrument.is_in_prefiller = False
        if "Spark 10M" in instrument.type:
            instrument.index_read_5_prime = "FORWARD"
            instrument.index_read_3_prime = "FORWARD"
        instrument.save()
        reversion.add_to_revision(instrument)

class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0066_v4_12_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='is_in_prefiller',
            field=models.BooleanField(default=True, help_text='Not all instruments are currently in use, this can determine which instrument type is displayed to the user.'),
        ),
        migrations.RunPython(
            remove_instrument_type_for_user,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
