# Generated by Django 4.2.4 on 2024-10-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0066_v4_12_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplekind',
            name='concentration_required',
        ),
    ]
