# Generated by Django 4.2.4 on 2025-10-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth import get_user_model

import reversion

ADMIN_USERNAME = 'biobankadmin'

def create_default_profile(apps, schema_editor):
    User = get_user_model()
    Profile = apps.get_model('fms_core', 'Profile')

    with reversion.create_revision(manage_manually=True):
        admin_user = User.objects.get(username=ADMIN_USERNAME)
        reversion.set_comment(f"Create default profile.")
        reversion.set_user(admin_user)

        default_profile = Profile.objects.create(
            name='Default',
            parent=None,
            preferences={
                "table.sample.page-limit": 20,
            },
            created_by_id=admin_user.id,
            updated_by_id=admin_user.id,
        )
        reversion.add_to_revision(default_profile)        

def create_freezeman_users(apps, schema_editor):
    Profile = apps.get_model('fms_core', 'Profile')
    FreezemanUser = apps.get_model('fms_core', 'FreezemanUser')

    default_profile = Profile.objects.get(name='Default')

    with reversion.create_revision(manage_manually=True):
        User = get_user_model()
        admin_user = User.objects.get(username=ADMIN_USERNAME)
        reversion.set_comment(f"Create FreezemanUser for all existing users.")
        reversion.set_user(admin_user)

        for user in User.objects.all():
            fm_user = FreezemanUser.objects.create(
                user_id=user.id,
                profile=default_profile,
                created_by_id=admin_user.id,
                updated_by_id=admin_user.id,
            )
            reversion.add_to_revision(fm_user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms_core', '0073_v5_3_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date the instance was modified.')),
                ('deleted', models.BooleanField(default=False, help_text='Whether this instance has been deleted.')),
                ('name', models.CharField(help_text="Name of the profile (e.g. 'TechDev', 'Production Lab', username, etc.)", max_length=50, unique=True)),
                ('preferences', models.JSONField(default=dict, help_text='Preferences stored as a JSON object')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fms_core.profile')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreezemanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the instance was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date the instance was modified.')),
                ('deleted', models.BooleanField(default=False, help_text='Whether this instance has been deleted.')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='fms_core.profile')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modification', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='freezeman_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_profile, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_freezeman_users, reverse_code=migrations.RunPython.noop),
    ]
