# Generated by Django 6.0.4 on 2026-09-23 18:53

import reversion

from django.contrib.auth import get_user_model
import django.db.models.deletion
from django.db import migrations, models

ADMIN_USERNAME = 'biobankadmin'

def add_trupath_virtual_library_type_to_trupath_illumina_workflow(apps, schema_editor):
    LibraryType = apps.get_model('fms_core', 'LibraryType')
    Workflow = apps.get_model('fms_core', 'Workflow')

    TRUPATH_WORKFLOW_NAME = "TruPath Illumina"
    TRUPATH_LIBRARY_TYPE = "TruPath"


    with reversion.create_revision(manage_manually=True):
        admin_user = get_user_model().objects.get(username=ADMIN_USERNAME)
        reversion.set_comment('Add virtual library to TruPath Illumina workflow.')
        reversion.set_user(admin_user)

        workflow = Workflow.objects.get(name=TRUPATH_WORKFLOW_NAME)
        library_type = LibraryType.objects.get(name=TRUPATH_LIBRARY_TYPE)

        workflow.virtual_library_type = library_type
        workflow.save()
        reversion.add_to_revision(workflow)

class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0082_v5_9_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='virtual_library_type',
            field=models.ForeignKey(blank=True, help_text='Library type for the library that gets created when doing experiment run preparation for workflows with virtual library preparation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libraryless_workflow', to='fms_core.librarytype'),
        ),
        migrations.AlterField(
            model_name='step',
            name='expected_sample_type',
            field=models.CharField(choices=[('ANY', 'Any'), ('UNEXTRACTED_SAMPLE', 'Unextracted sample'), ('EXTRACTED_SAMPLE', 'Extracted sample'), ('EXTRACTED_SAMPLE_OR_LIBRARY', 'Extracted sample or library'), ('SAMPLE', 'Sample'), ('LIBRARY', 'Library'), ('POOL', 'Pooled library')], default='ANY', help_text='The acceptable sample type for the step.', max_length=200),
        ),
        migrations.AlterField(
            model_name='stephistory',
            name='workflow_action',
            field=models.CharField(choices=[('NEXT_STEP', 'Step complete - Move to next step'), ('DEQUEUE_SAMPLE', 'Sample failed - Remove sample from study workflow'), ('REPEAT_STEP', 'Repeat step - Move to next step and repeat current step'), ('REPEAT_QC_STEP', 'Repeat QC step - Repeat current QC step'), ('SKIP_STEP', 'Skip step - Skip to next step'), ('IGNORE_WORKFLOW', 'Ignore workflow - Do not register as part of a workflow')], default='NEXT_STEP', help_text='Workflow action that was performed on the sample after step completion.', max_length=30),
        ),
        migrations.AlterField(
            model_name='steporder',
            name='mandatory',
            field=models.BooleanField(default=True, help_text='Indicates that this step cannot be skipped in this workflow.'),
        ),
        migrations.RunPython(add_trupath_virtual_library_type_to_trupath_illumina_workflow, reverse_code=migrations.RunPython.noop)
    ]
