# Generated by Django 6.0.4 on 2026-09-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0082_v5_9_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='expected_sample_type',
            field=models.CharField(choices=[('ANY', 'Any'), ('UNEXTRACTED_SAMPLE', 'Unextracted sample'), ('EXTRACTED_SAMPLE', 'Extracted sample'), ('EXTRACTED_SAMPLE_OR_LIBRARY', 'Extracted sample or library'), ('SAMPLE', 'Sample'), ('LIBRARY', 'Library'), ('POOL', 'Pooled library')], default='ANY', help_text='The acceptable sample type for the step.', max_length=200),
        ),
        migrations.AlterField(
            model_name='stephistory',
            name='workflow_action',
            field=models.CharField(choices=[('NEXT_STEP', 'Step complete - Move to next step'), ('DEQUEUE_SAMPLE', 'Sample failed - Remove sample from study workflow'), ('REPEAT_STEP', 'Repeat step - Move to next step and repeat current step'), ('REPEAT_QC_STEP', 'Repeat QC step - Repeat current QC step'), ('SKIP_STEP', 'Skip step - Skip to next step'), ('IGNORE_WORKFLOW', 'Ignore workflow - Do not register as part of a workflow')], default='NEXT_STEP', help_text='Workflow action that was performed on the sample after step completion.', max_length=30),
        ),
        migrations.AlterField(
            model_name='steporder',
            name='mandatory',
            field=models.BooleanField(default=True, help_text='Indicates that this step cannot be skipped in this workflow.'),
        ),
    ]
