# Generated by Django 6.0.4 on 2026-10-09 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_report', '0002_v5_0_0'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metricfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the instance was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metricfield',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metricfield',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether this instance has been deleted.'),
        ),
        migrations.AddField(
            model_name='metricfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date the instance was modified.'),
        ),
        migrations.AddField(
            model_name='metricfield',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modification', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productiondata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the instance was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productiondata',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productiondata',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether this instance has been deleted.'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date the instance was modified.'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modification', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the instance was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether this instance has been deleted.'),
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date the instance was modified.'),
        ),
        migrations.AddField(
            model_name='productiontracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modification', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the instance was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether this instance has been deleted.'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date the instance was modified.'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modification', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
