FROM docker.io/library/python:3.11.14-slim-bookworm

WORKDIR /freezeman/backend/

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    git

RUN pip install -r requirements.txt
