FROM docker.io/library/node:25.2.1-alpine3.23 AS builder

RUN apk add --no-cache git

WORKDIR /app/frontend

COPY ./frontend/package*.json ./

RUN npm ci --no-audit --no-fund

COPY ./frontend/ /app/frontend/
COPY ./.git ./VERSION /app/

RUN npm run build

FROM docker.io/library/nginx:1.29.4-alpine AS runtime

COPY ./docker/frontend.nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/dist/. /usr/share/nginx/html

EXPOSE 80

# use default ENTRYPOINT and CMD of nginx image