FROM docker.io/library/python:3.11.14-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends build-essential libffi-dev git

# Set the working directory inside the container
WORKDIR /app/backend/

# Set environment variables 
# Prevents Python from writing pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1
#Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED=1 

# run this command to install all dependencies 
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Django port
EXPOSE 8000

# Run Django’s development server
ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
