# Generated by Django 3.0.5 on 2020-04-06 14:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('kind', models.CharField(choices=[('96-well plate', '96-well plate'), ('384-well plate', '384-well plate'), ('tube', 'tube'), ('tube box 9x9', 'tube box 9x9'), ('tube box 10x10', 'tube box 10x10'), ('tube rack 8x12', 'tube rack 8x12'), ('drawer', 'drawer'), ('freezer rack', 'freezer rack'), ('freezer', 'freezer'), ('room', 'room'), ('box', 'box')], max_length=20)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('barcode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('coordinates', models.CharField(blank=True, max_length=20)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fms_core.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('participant_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('taxon', models.CharField(choices=[('Homo sapiens', 'Homo sapiens'), ('Mus musculus', 'Mus musculus')], max_length=20)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Unknown', 'Unknown')], max_length=10)),
                ('pedigree', models.CharField(blank=True, max_length=200)),
                ('cohort', models.CharField(blank=True, max_length=200)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_of', to='fms_core.Individual')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_of', to='fms_core.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('biospecimen_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('BLOOD', 'BLOOD'), ('SALIVA', 'SALIVA')], max_length=200)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('volume', models.CharField(blank=True, help_text='Volume, µL', max_length=200)),
                ('concentration', models.CharField(blank=True, help_text='Concentration, ', max_length=200)),
                ('depleted', models.BooleanField(default=False)),
                ('experimental_group', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('collection_site', models.CharField(max_length=200)),
                ('tissue_source', models.CharField(blank=True, max_length=200)),
                ('reception_date', models.DateField()),
                ('phenotype', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('coordinates', models.CharField(blank=True, max_length=10)),
                ('volume_used', models.CharField(max_length=200)),
                ('container', models.ForeignKey(limit_choices_to={'kind__in': ('96-well plate', '384-well plate', 'tube')}, on_delete=django.db.models.deletion.PROTECT, to='fms_core.Container')),
                ('extracted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fms_core.Sample')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fms_core.Individual')),
            ],
        ),
    ]
