# Generated by Django 3.0.5 on 2020-04-07 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='barcode',
            field=models.CharField(help_text='Unique container barcode.', max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9.-_]*$'))]),
        ),
        migrations.AlterField(
            model_name='container',
            name='location',
            field=models.ForeignKey(blank=True, help_text='An existing (parent) container this container is located inside of.', limit_choices_to={'kind__in': ('tube box 9x9', 'tube box 10x10', 'tube rack 8x12', 'drawer', 'freezer rack', 'freezer', 'room', 'box')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='fms_core.Container'),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(help_text='Unique name for the container.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9.-_]*$'))]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9.-_]*$'))]),
        ),
    ]
