# Generated by Django 3.0.5 on 2020-04-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fms_core.Container'),
        ),
    ]
