# Generated by Django 3.0.5 on 2020-04-08 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='reception_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 21, 37, 1, 90193, tzinfo=utc)),
        ),
    ]
