# Generated by Django 3.0.5 on 2020-04-10 20:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.manager
import fms_core.schema_validators


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerMove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fms_core.container',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SampleUpdate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fms_core.sample',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='individual',
            name='participant_id',
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='volume_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[fms_core.schema_validators.JsonSchemaValidator({'$id': 'fms:volume', '$schema': 'http://json-schema.org/draft-07/schema#', 'description': 'Schema used to define volume and its updates.', 'items': {'additionalProperties': False, 'if': {'properties': {'update_type': {'const': ['extraction']}}, 'required': ['extracted_sample_id']}, 'properties': {'date': {'format': 'date-time', 'type': 'string'}, 'extracted_sample_id': {'type': 'integer'}, 'update_type': {'enum': ['extraction', 'update'], 'type': 'string'}, 'volume_value': {'type': 'string'}}, 'required': ['update_type', 'volume_value', 'date'], 'type': 'object'}, 'minItems': 1, 'title': 'Volume schema', 'type': 'array'})]),
        ),
    ]
