# Generated by Django 3.0.5 on 2020-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0002_auto_20200407_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
