# Generated by Django 3.0.5 on 2020-04-08 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0002_auto_20200408_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='reception_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
