# Generated by Django 3.0.5 on 2020-04-13 23:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import fms_core.schema_validators


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0002_auto_20200410_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='concentration',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Concentration in ng/µL. Required for nucleic acid samples.', max_digits=20, null=True, verbose_name='concentration in ng/µL'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='extracted_from',
            field=models.ForeignKey(blank=True, help_text='The sample this sample was extracted from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='fms_core.Sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='volume_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[fms_core.schema_validators.JsonSchemaValidator({'$id': 'fms:volume', '$schema': 'http://json-schema.org/draft-07/schema#', 'description': 'Schema used to define volume and its updates.', 'items': {'additionalProperties': False, 'if': {'properties': {'update_type': {'const': ['extraction']}}, 'required': ['extracted_sample_id']}, 'properties': {'date': {'format': 'date-time', 'type': 'string'}, 'extracted_sample_id': {'type': 'integer'}, 'update_type': {'enum': ['extraction', 'update'], 'type': 'string'}, 'volume_value': {'type': 'string'}}, 'required': ['update_type', 'volume_value', 'date'], 'type': 'object'}, 'minItems': 1, 'title': 'Volume schema', 'type': 'array'})], verbose_name='volume history in µL'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='volume_used',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volume of the original sample used for the extraction, in µL.', max_digits=20, null=True),
        ),
    ]
