# Generated by Django 3.0.5 on 2020-04-08 21:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import fms_core.schema_validators


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0003_auto_20200408_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='volume_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[fms_core.schema_validators.JsonSchemaValidator({'$id': 'fms:volume', '$schema': 'http://json-schema.org/draft-07/schema#', 'description': 'Schema used to define volume and its updates.', 'items': {'additionalProperties': False, 'if': {'properties': {'update_type': {'const': ['extraction']}}, 'required': ['extracted_sample_id']}, 'properties': {'date': {'format': 'date', 'type': 'string'}, 'extracted_sample_id': {'type': 'string'}, 'update_type': {'enum': ['extraction', 'update'], 'type': 'string'}, 'volume_value': {'type': 'string'}}, 'required': ['update_type', 'volume_value', 'date'], 'type': 'object'}, 'title': 'Volume schema', 'type': 'array'})]),
        ),
    ]
