# Generated by Django 3.0.5 on 2020-04-07 22:54

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0003_container_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='barcode',
            field=models.CharField(help_text='Unique container barcode.', max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9.-_]+$'))]),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(help_text='Unique name for the container.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9.-_]+$'))]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9.-_]+$'))]),
        ),
    ]
