# Generated by Django 3.0.5 on 2020-04-14 16:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import fms_core.schema_validators


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0003_auto_20200413_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='experimental_group',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, validators=[fms_core.schema_validators.JsonSchemaValidator({'$id': 'fms:experimental_group', '$schema': 'http://json-schema.org/draft-07/schema#', 'description': 'Schema used to define experimental groups for a sample.', 'items': {'type': 'string'}, 'title': 'Experimental group schema', 'type': 'array', 'uniqueItems': True})]),
        ),
    ]
