# Generated by Django 3.0.5 on 2020-04-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0004_auto_20200414_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='tissue_source',
            field=models.CharField(blank=True, choices=[('Blood', 'Blood'), ('Saliva', 'Saliva'), ('Tumor', 'Tumor'), ('Plasma', 'Plasma'), ('Buffy coat', 'Buffy coat'), ('Tail', 'Tail'), ('Cells', 'Cells')], max_length=200),
        ),
    ]
