# Generated by Django 3.0.5 on 2020-04-08 18:20

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0004_auto_20200407_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedSample',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fms_core.sample',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='reception_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 18, 20, 27, 93267, tzinfo=utc)),
        ),
    ]
