# Generated by Django 3.0.5 on 2020-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0007_auto_20200423_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='name',
            new_name='id',
        ),
    ]
