# Generated by Django 3.1 on 2020-10-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0007_v2_3_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='id',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='individual',
            name='father',
            field=models.CharField(blank=True, help_text='Father of the individual.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='mother',
            field=models.CharField(blank=True, help_text='Mother of the individual.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='individual',
            field=models.CharField(help_text='Individual associated with the sample.', max_length=200),
        ),
        migrations.RunSQL(
            "ALTER TABLE fms_core_individual DROP CONSTRAINT fms_core_individual_pkey",
            "ALTER TABLE fms_core_individual_temp ADD PRIMARY KEY (label)"
        ),
        migrations.RunSQL(
            "CREATE TABLE fms_core_individual_temp AS TABLE fms_core_individual",
            "DROP TABLE fms_core_individual_temp"
        ),
        migrations.RunSQL(
            "DROP TABLE fms_core_individual",

        ),
        migrations.RunSQL(
            "CREATE TABLE fms_core_individual AS TABLE fms_core_individual_temp WITH NO DATA",
            "DROP TABLE fms_core_individual"
        ),
        migrations.AddField(
            model_name='individual',
            name='id',
            field=models.AutoField(primary_key=True),
        ),
        migrations.RunSQL(
            "INSERT INTO fms_core_individual SELECT * FROM fms_core_individual_temp",
            migrations.RunSQL.noop
        ),
    ]
