# Generated by Django 3.0.5 on 2020-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0008_auto_20200424_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
