# Generated by Django 3.0.5 on 2020-04-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms_core', '0009_importedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedfile',
            name='imported_file',
        ),
        migrations.AddField(
            model_name='importedfile',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importedfile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
