# Generated by Django 3.1 on 2020-12-07 20:54

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0009_v2_6_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='barcode',
            field=models.CharField(help_text='Unique container barcode.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[^\\$]{1,199}$'))]),
        ),
    ]
