# Generated by Django 3.0.5 on 2020-04-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0010_auto_20200428_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedfile',
            name='filename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='importedfile',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
