# Generated by Django 3.0.6 on 2020-05-06 14:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import fms_core.schema_validators


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0011_auto_20200428_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='biospecimen_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('BLOOD', 'BLOOD'), ('SALIVA', 'SALIVA'), ('SWAB', 'SWAB')], help_text='Biological material collected from study subject during the conduct of a genomic study project.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sample',
            name='experimental_group',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Sample group having some common characteristics. It is the way to designate a subgroup within a study.', validators=[fms_core.schema_validators.JsonSchemaValidator({'$id': 'fms:experimental_group', '$schema': 'http://json-schema.org/draft-07/schema#', 'description': 'Schema used to define experimental groups for a sample.', 'items': {'minLength': 1, 'type': 'string'}, 'title': 'Experimental group schema', 'type': 'array', 'uniqueItems': True}, formats=None)]),
        ),
    ]
