# Generated by Django 3.0.6 on 2020-05-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0012_auto_20200506_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='update_comment',
            field=models.TextField(blank=True, help_text='Comment describing the latest updates made to the sample. Change this whenever updates are made.'),
        ),
    ]
