# Generated by Django 3.0.6 on 2020-05-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0013_sample_update_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='update_comment',
            field=models.TextField(blank=True, help_text='Comment describing the latest updates made to the container. Change this whenever updates are made.'),
        ),
    ]
