# Normalization planning
FIXED_FORMAT = "Fixed (plates)"
MOBILE_FORMAT = "Mobile (tubes)"
VALID_ROBOT_FORMATS = [FIXED_FORMAT, MOBILE_FORMAT]
SAMPLE_CHOICE = "Sample"
LIBRARY_CHOICE = "Library"
VALID_NORM_CHOICES = [SAMPLE_CHOICE, LIBRARY_CHOICE]