# Normalization planning
SAMPLE_BIOMEK_CHOICE = "Sample Biomek"
SAMPLE_JANUS_CHOICE = "Sample Janus"
LIBRARY_CHOICE = "Library"
VALID_NORM_CHOICES = [SAMPLE_BIOMEK_CHOICE, SAMPLE_JANUS_CHOICE, LIBRARY_CHOICE]