__all__ = ["STANDARD_NAME_FIELD_LENGTH"]

STANDARD_NAME_FIELD_LENGTH = 200
STANDARD_SEQUENCE_FIELD_LENGTH = 500
PROJECT_STATUS_CHOICES = ["Open", "Closed"]
INDEX_READ_FORWARD = "FORWARD"
INDEX_READ_REVERSE = "REVERSE"
INDEX_READ_DIRECTIONS_CHOICES = ((INDEX_READ_FORWARD, INDEX_READ_FORWARD), (INDEX_READ_REVERSE, INDEX_READ_REVERSE))
