import { AnyAction } from "redux"

export const LOAD_SOURCE_SAMPLES = 'PLACEMENT:LOAD_SOURCE_SAMPLES'
export const LOAD_DESTINATION_CONTAINER = 'PLACEMENT:LOAD_DESTINATION_CONTAINER'

export const CLICK_CELL = 'PLACEMENT:CLICK_CELL'
export const MOUSE_ENTER_CELL = 'PLACEMENT:MOUSE_ENTER_CELL'
export const MOUSE_EXIT_CELL = 'PLACEMENT_MOUSE_EXIT'

export const SELECT_ALL = 'PLACEMENT:DESELECT_ALL'
export const DESELECT_ALL = 'PLACEMENT:DESELECT_ALL'
export const SELECT_ROW = 'PLACEMENT:SELECT_ROW'
export const SELECT_COLUMN = 'PLACEMENT:SELECT_COLUMN'

export const PLACE_ALL = 'PLACEMENT:PLACE_ALL'
export const UNDO_ALL = 'PLACEMENT:UNDO_ALL'

export default {
    LOAD_SOURCE_SAMPLES,
    LOAD_DESTINATION_CONTAINER,

    CLICK_CELL,
    MOUSE_ENTER_CELL,
    MOUSE_EXIT_CELL,

    SELECT_ALL,
    DESELECT_ALL,
    SELECT_ROW,
    SELECT_COLUMN,

    PLACE_ALL,
    UNDO_ALL
}
